//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 04:22:14 ip. EET 
//


package eta3;

import javax.xml.bind.annotation.XmlRegistry;

import tyontekija.Tyontekijat;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eta3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eta3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tyontekijat }
     * 
     */
    public Tyontekijat createTyontekijat() {
        return new Tyontekijat();
    }

    /**
     * Create an instance of {@link Tyontekijat.Tyontekija }
     * 
     */
    public Tyontekijat.Tyontekija createTyontekijatTyontekija() {
        return new Tyontekijat.Tyontekija();
    }

    /**
     * Create an instance of {@link Tyontekijat.Tyontekija.Etunimi }
     * 
     */
    public Tyontekijat.Tyontekija.Etunimi createTyontekijatTyontekijaEtunimi() {
        return new Tyontekijat.Tyontekija.Etunimi();
    }

    /**
     * Create an instance of {@link Tyontekijat.Tyontekija.Osasto }
     * 
     */
    public Tyontekijat.Tyontekija.Osasto createTyontekijatTyontekijaOsasto() {
        return new Tyontekijat.Tyontekija.Osasto();
    }

}
