//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 04:22:14 ip. EET 
//


package tyontekija;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tyontekija" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sukunimi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="etunimi" maxOccurs="3">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="kutsuma" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="palkka" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="osasto" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="nimi" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="asema" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tyontekija"
})
@XmlRootElement(name = "tyontekijat")
public class Tyontekijat {

    @XmlElement(required = true)
    protected List<Tyontekijat.Tyontekija> tyontekija;

    /**
     * Gets the value of the tyontekija property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tyontekija property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTyontekija().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tyontekijat.Tyontekija }
     * 
     * 
     */
    public List<Tyontekijat.Tyontekija> getTyontekija() {
        if (tyontekija == null) {
            tyontekija = new ArrayList<Tyontekijat.Tyontekija>();
        }
        return this.tyontekija;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sukunimi" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="etunimi" maxOccurs="3">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="kutsuma" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="palkka" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="osasto" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="nimi" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="asema" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sukunimi",
        "etunimi",
        "palkka",
        "osasto"
    })
    public static class Tyontekija {

        @XmlElement(required = true)
        protected String sukunimi;
        @XmlElement(required = true)
        protected List<Tyontekijat.Tyontekija.Etunimi> etunimi;
        protected BigDecimal palkka;
        protected Tyontekijat.Tyontekija.Osasto osasto;
        @XmlAttribute(name = "asema")
        protected String asema;
        @XmlAttribute(name = "id", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long id;

        /**
         * Gets the value of the sukunimi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSukunimi() {
            return sukunimi;
        }

        /**
         * Sets the value of the sukunimi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSukunimi(String value) {
            this.sukunimi = value;
        }

        /**
         * Gets the value of the etunimi property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the etunimi property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEtunimi().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tyontekijat.Tyontekija.Etunimi }
         * 
         * 
         */
        public List<Tyontekijat.Tyontekija.Etunimi> getEtunimi() {
            if (etunimi == null) {
                etunimi = new ArrayList<Tyontekijat.Tyontekija.Etunimi>();
            }
            return this.etunimi;
        }

        /**
         * Gets the value of the palkka property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPalkka() {
            return palkka;
        }

        /**
         * Sets the value of the palkka property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPalkka(BigDecimal value) {
            this.palkka = value;
        }

        /**
         * Gets the value of the osasto property.
         * 
         * @return
         *     possible object is
         *     {@link Tyontekijat.Tyontekija.Osasto }
         *     
         */
        public Tyontekijat.Tyontekija.Osasto getOsasto() {
            return osasto;
        }

        /**
         * Sets the value of the osasto property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tyontekijat.Tyontekija.Osasto }
         *     
         */
        public void setOsasto(Tyontekijat.Tyontekija.Osasto value) {
            this.osasto = value;
        }

        /**
         * Gets the value of the asema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAsema() {
            return asema;
        }

        /**
         * Sets the value of the asema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAsema(String value) {
            this.asema = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="kutsuma" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Etunimi {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "kutsuma")
            protected String kutsuma;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the kutsuma property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKutsuma() {
                return kutsuma;
            }

            /**
             * Sets the value of the kutsuma property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKutsuma(String value) {
                this.kutsuma = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="nimi" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Osasto {

            @XmlAttribute(name = "nimi", required = true)
            protected String nimi;

            /**
             * Gets the value of the nimi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNimi() {
                return nimi;
            }

            /**
             * Sets the value of the nimi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNimi(String value) {
                this.nimi = value;
            }

        }

    }

}
